name: Generate Snake Animation

on:
  schedule:
    # Her gün 23:00'te çalışır.
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Snake animation için veri indir
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Snake animation oluştur
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: mustafaemirata
          outputs: dist/snake.svg

      # Snake animasyonu GitHub Pages'a yükle
      - name: Push Snake Animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
